# Generated by Django 3.0.3 on 2020-04-20 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Objetos_Dororo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('procedencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='demonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=20)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Lugar')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Parte')),
            ],
        ),
        migrations.CreateModel(
            name='Batalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador', models.CharField(max_length=25)),
                ('Demonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.demonio')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Lugar')),
            ],
        ),
    ]
